included:
  - "Sources"
excluded: 
  - "Sources/Exporters/OpenTelemetryProtocolCommon/proto"
  - ".build"
disabled_rules:
  - nesting
  - line_length
  - type_body_length
  - identifier_name
  - file_length
  - force_cast
  - type_name
  - large_tuple
  - function_body_length
  - function_parameter_count
  - cyclomatic_complexity
  - force_try
