/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  public enum Gcp: String {

    /**
     The container within GCP where the AppHub application is defined.

      - Examples:
      ```
      attributes[SemanticConventions.Gcp.apphubApplicationContainer.rawValue] = "projects/my-container-project"
      ```

     - Requires: Value type should be `String`
    */
    case apphubApplicationContainer = "gcp.apphub.application.container"

    /**
     The name of the application as configured in AppHub.

      - Examples:
      ```
      attributes[SemanticConventions.Gcp.apphubApplicationId.rawValue] = "my-application"
      ```

     - Requires: Value type should be `String`
    */
    case apphubApplicationId = "gcp.apphub.application.id"

    /**
     The GCP zone or region where the application is defined.

      - Examples:
      ```
      attributes[SemanticConventions.Gcp.apphubApplicationLocation.rawValue] = "us-central1"
      ```

     - Requires: Value type should be `String`
    */
    case apphubApplicationLocation = "gcp.apphub.application.location"

    /**
     Criticality of a service indicates its importance to the business.

     - Note: [See AppHub type enum](https://cloud.google.com/app-hub/docs/reference/rest/v1/Attributes#type)

     - Requires: Value should be one of ``ApphubServiceCriticalityTypeValues`` (of type `String`)
    */
    case apphubServiceCriticalityType = "gcp.apphub.service.criticality_type"

    /**
     Environment of a service is the stage of a software lifecycle.

     - Note: [See AppHub environment type](https://cloud.google.com/app-hub/docs/reference/rest/v1/Attributes#type_1)

     - Requires: Value should be one of ``ApphubServiceEnvironmentTypeValues`` (of type `String`)
    */
    case apphubServiceEnvironmentType = "gcp.apphub.service.environment_type"

    /**
     The name of the service as configured in AppHub.

      - Examples:
      ```
      attributes[SemanticConventions.Gcp.apphubServiceId.rawValue] = "my-service"
      ```

     - Requires: Value type should be `String`
    */
    case apphubServiceId = "gcp.apphub.service.id"

    /**
     Criticality of a workload indicates its importance to the business.

     - Note: [See AppHub type enum](https://cloud.google.com/app-hub/docs/reference/rest/v1/Attributes#type)

     - Requires: Value should be one of ``ApphubWorkloadCriticalityTypeValues`` (of type `String`)
    */
    case apphubWorkloadCriticalityType = "gcp.apphub.workload.criticality_type"

    /**
     Environment of a workload is the stage of a software lifecycle.

     - Note: [See AppHub environment type](https://cloud.google.com/app-hub/docs/reference/rest/v1/Attributes#type_1)

     - Requires: Value should be one of ``ApphubWorkloadEnvironmentTypeValues`` (of type `String`)
    */
    case apphubWorkloadEnvironmentType = "gcp.apphub.workload.environment_type"

    /**
     The name of the workload as configured in AppHub.

      - Examples:
      ```
      attributes[SemanticConventions.Gcp.apphubWorkloadId.rawValue] = "my-workload"
      ```

     - Requires: Value type should be `String`
    */
    case apphubWorkloadId = "gcp.apphub.workload.id"

    /**
     The container within GCP where the AppHub destination application is defined.

      - Examples:
      ```
      attributes[SemanticConventions.Gcp.apphubDestinationApplicationContainer.rawValue] = "projects/my-container-project"
      ```

     - Requires: Value type should be `String`
    */
    case apphubDestinationApplicationContainer = "gcp.apphub_destination.application.container"

    /**
     The name of the destination application as configured in AppHub.

      - Examples:
      ```
      attributes[SemanticConventions.Gcp.apphubDestinationApplicationId.rawValue] = "my-application"
      ```

     - Requires: Value type should be `String`
    */
    case apphubDestinationApplicationId = "gcp.apphub_destination.application.id"

    /**
     The GCP zone or region where the destination application is defined.

      - Examples:
      ```
      attributes[SemanticConventions.Gcp.apphubDestinationApplicationLocation.rawValue] = "us-central1"
      ```

     - Requires: Value type should be `String`
    */
    case apphubDestinationApplicationLocation = "gcp.apphub_destination.application.location"

    /**
     Criticality of a destination workload indicates its importance to the business as specified in [AppHub type enum](https://cloud.google.com/app-hub/docs/reference/rest/v1/Attributes#type)

     - Requires: Value should be one of ``ApphubDestinationServiceCriticalityTypeValues`` (of type `String`)
    */
    case apphubDestinationServiceCriticalityType = "gcp.apphub_destination.service.criticality_type"

    /**
     Software lifecycle stage of a destination service as defined [AppHub environment type](https://cloud.google.com/app-hub/docs/reference/rest/v1/Attributes#type_1)

     - Requires: Value should be one of ``ApphubDestinationServiceEnvironmentTypeValues`` (of type `String`)
    */
    case apphubDestinationServiceEnvironmentType = "gcp.apphub_destination.service.environment_type"

    /**
     The name of the destination service as configured in AppHub.

      - Examples:
      ```
      attributes[SemanticConventions.Gcp.apphubDestinationServiceId.rawValue] = "my-service"
      ```

     - Requires: Value type should be `String`
    */
    case apphubDestinationServiceId = "gcp.apphub_destination.service.id"

    /**
     Criticality of a destination workload indicates its importance to the business as specified in [AppHub type enum](https://cloud.google.com/app-hub/docs/reference/rest/v1/Attributes#type)

     - Requires: Value should be one of ``ApphubDestinationWorkloadCriticalityTypeValues`` (of type `String`)
    */
    case apphubDestinationWorkloadCriticalityType = "gcp.apphub_destination.workload.criticality_type"

    /**
     Environment of a destination workload is the stage of a software lifecycle as provided in the [AppHub environment type](https://cloud.google.com/app-hub/docs/reference/rest/v1/Attributes#type_1)

     - Requires: Value should be one of ``ApphubDestinationWorkloadEnvironmentTypeValues`` (of type `String`)
    */
    case apphubDestinationWorkloadEnvironmentType = "gcp.apphub_destination.workload.environment_type"

    /**
     The name of the destination workload as configured in AppHub.

      - Examples:
      ```
      attributes[SemanticConventions.Gcp.apphubDestinationWorkloadId.rawValue] = "my-workload"
      ```

     - Requires: Value type should be `String`
    */
    case apphubDestinationWorkloadId = "gcp.apphub_destination.workload.id"

    /**
     Identifies the Google Cloud service for which the official client library is intended.

      - Examples:
      ```
      attributes[SemanticConventions.Gcp.clientService.rawValue] = "appengine"
      attributes[SemanticConventions.Gcp.clientService.rawValue] = "run"
      attributes[SemanticConventions.Gcp.clientService.rawValue] = "firestore"
      attributes[SemanticConventions.Gcp.clientService.rawValue] = "alloydb"
      attributes[SemanticConventions.Gcp.clientService.rawValue] = "spanner"
      ```

     - Note: Intended to be a stable identifier for Google Cloud client libraries that is uniform across implementation languages. The value should be derived from the canonical service domain for the service; for example, 'foo.googleapis.com' should result in a value of 'foo'.

     - Requires: Value type should be `String`
    */
    case clientService = "gcp.client.service"

    /**
     The name of the Cloud Run [execution](https://cloud.google.com/run/docs/managing/job-executions) being run for the Job, as set by the [`CLOUD_RUN_EXECUTION`](https://cloud.google.com/run/docs/container-contract#jobs-env-vars) environment variable.

      - Examples:
      ```
      attributes[SemanticConventions.Gcp.cloudRunJobExecution.rawValue] = "job-name-xxxx"
      attributes[SemanticConventions.Gcp.cloudRunJobExecution.rawValue] = "sample-job-mdw84"
      ```

     - Requires: Value type should be `String`
    */
    case cloudRunJobExecution = "gcp.cloud_run.job.execution"

    /**
     The index for a task within an execution as provided by the [`CLOUD_RUN_TASK_INDEX`](https://cloud.google.com/run/docs/container-contract#jobs-env-vars) environment variable.

      - Examples:
      ```
      attributes[SemanticConventions.Gcp.cloudRunJobTaskIndex.rawValue] = 0
      attributes[SemanticConventions.Gcp.cloudRunJobTaskIndex.rawValue] = 1
      ```

     - Requires: Value type should be `Int`
    */
    case cloudRunJobTaskIndex = "gcp.cloud_run.job.task_index"

    /**
     The hostname of a GCE instance. This is the full value of the default or [custom hostname](https://cloud.google.com/compute/docs/instances/custom-hostname-vm).

      - Examples:
      ```
      attributes[SemanticConventions.Gcp.gceInstanceHostname.rawValue] = "my-host1234.example.com"
      attributes[SemanticConventions.Gcp.gceInstanceHostname.rawValue] = "sample-vm.us-west1-b.c.my-project.internal"
      ```

     - Requires: Value type should be `String`
    */
    case gceInstanceHostname = "gcp.gce.instance.hostname"

    /**
     The instance name of a GCE instance. This is the value provided by `host.name`, the visible name of the instance in the Cloud Console UI, and the prefix for the default hostname of the instance as defined by the [default internal DNS name](https://cloud.google.com/compute/docs/internal-dns#instance-fully-qualified-domain-names).

      - Examples:
      ```
      attributes[SemanticConventions.Gcp.gceInstanceName.rawValue] = "instance-1"
      attributes[SemanticConventions.Gcp.gceInstanceName.rawValue] = "my-vm-name"
      ```

     - Requires: Value type should be `String`
    */
    case gceInstanceName = "gcp.gce.instance.name"

    /** 
      Criticality of a service indicates its importance to the business.
    */
    public struct ApphubServiceCriticalityTypeValues: CustomStringConvertible, Sendable {
      
      /// Mission critical service.
      public static let missionCritical = ApphubServiceCriticalityTypeValues("MISSION_CRITICAL") 
      
      /// High impact.
      public static let high = ApphubServiceCriticalityTypeValues("HIGH") 
      
      /// Medium impact.
      public static let medium = ApphubServiceCriticalityTypeValues("MEDIUM") 
      
      /// Low impact.
      public static let low = ApphubServiceCriticalityTypeValues("LOW") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      Environment of a service is the stage of a software lifecycle.
    */
    public struct ApphubServiceEnvironmentTypeValues: CustomStringConvertible, Sendable {
      
      /// Production environment.
      public static let production = ApphubServiceEnvironmentTypeValues("PRODUCTION") 
      
      /// Staging environment.
      public static let staging = ApphubServiceEnvironmentTypeValues("STAGING") 
      
      /// Test environment.
      public static let test = ApphubServiceEnvironmentTypeValues("TEST") 
      
      /// Development environment.
      public static let development = ApphubServiceEnvironmentTypeValues("DEVELOPMENT") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      Criticality of a workload indicates its importance to the business.
    */
    public struct ApphubWorkloadCriticalityTypeValues: CustomStringConvertible, Sendable {
      
      /// Mission critical service.
      public static let missionCritical = ApphubWorkloadCriticalityTypeValues("MISSION_CRITICAL") 
      
      /// High impact.
      public static let high = ApphubWorkloadCriticalityTypeValues("HIGH") 
      
      /// Medium impact.
      public static let medium = ApphubWorkloadCriticalityTypeValues("MEDIUM") 
      
      /// Low impact.
      public static let low = ApphubWorkloadCriticalityTypeValues("LOW") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      Environment of a workload is the stage of a software lifecycle.
    */
    public struct ApphubWorkloadEnvironmentTypeValues: CustomStringConvertible, Sendable {
      
      /// Production environment.
      public static let production = ApphubWorkloadEnvironmentTypeValues("PRODUCTION") 
      
      /// Staging environment.
      public static let staging = ApphubWorkloadEnvironmentTypeValues("STAGING") 
      
      /// Test environment.
      public static let test = ApphubWorkloadEnvironmentTypeValues("TEST") 
      
      /// Development environment.
      public static let development = ApphubWorkloadEnvironmentTypeValues("DEVELOPMENT") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      Criticality of a destination workload indicates its importance to the business as specified in [AppHub type enum](https://cloud.google.com/app-hub/docs/reference/rest/v1/Attributes#type)
    */
    public struct ApphubDestinationServiceCriticalityTypeValues: CustomStringConvertible, Sendable {
      
      /// Mission critical service.
      public static let missionCritical = ApphubDestinationServiceCriticalityTypeValues("MISSION_CRITICAL") 
      
      /// High impact.
      public static let high = ApphubDestinationServiceCriticalityTypeValues("HIGH") 
      
      /// Medium impact.
      public static let medium = ApphubDestinationServiceCriticalityTypeValues("MEDIUM") 
      
      /// Low impact.
      public static let low = ApphubDestinationServiceCriticalityTypeValues("LOW") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      Software lifecycle stage of a destination service as defined [AppHub environment type](https://cloud.google.com/app-hub/docs/reference/rest/v1/Attributes#type_1)
    */
    public struct ApphubDestinationServiceEnvironmentTypeValues: CustomStringConvertible, Sendable {
      
      /// Production environment.
      public static let production = ApphubDestinationServiceEnvironmentTypeValues("PRODUCTION") 
      
      /// Staging environment.
      public static let staging = ApphubDestinationServiceEnvironmentTypeValues("STAGING") 
      
      /// Test environment.
      public static let test = ApphubDestinationServiceEnvironmentTypeValues("TEST") 
      
      /// Development environment.
      public static let development = ApphubDestinationServiceEnvironmentTypeValues("DEVELOPMENT") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      Criticality of a destination workload indicates its importance to the business as specified in [AppHub type enum](https://cloud.google.com/app-hub/docs/reference/rest/v1/Attributes#type)
    */
    public struct ApphubDestinationWorkloadCriticalityTypeValues: CustomStringConvertible, Sendable {
      
      /// Mission critical service.
      public static let missionCritical = ApphubDestinationWorkloadCriticalityTypeValues("MISSION_CRITICAL") 
      
      /// High impact.
      public static let high = ApphubDestinationWorkloadCriticalityTypeValues("HIGH") 
      
      /// Medium impact.
      public static let medium = ApphubDestinationWorkloadCriticalityTypeValues("MEDIUM") 
      
      /// Low impact.
      public static let low = ApphubDestinationWorkloadCriticalityTypeValues("LOW") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }

    /** 
      Environment of a destination workload is the stage of a software lifecycle as provided in the [AppHub environment type](https://cloud.google.com/app-hub/docs/reference/rest/v1/Attributes#type_1)
    */
    public struct ApphubDestinationWorkloadEnvironmentTypeValues: CustomStringConvertible, Sendable {
      
      /// Production environment.
      public static let production = ApphubDestinationWorkloadEnvironmentTypeValues("PRODUCTION") 
      
      /// Staging environment.
      public static let staging = ApphubDestinationWorkloadEnvironmentTypeValues("STAGING") 
      
      /// Test environment.
      public static let test = ApphubDestinationWorkloadEnvironmentTypeValues("TEST") 
      
      /// Development environment.
      public static let development = ApphubDestinationWorkloadEnvironmentTypeValues("DEVELOPMENT") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }
  }
}