/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  public enum Linux: String {

    /**
     The Linux Slab memory state

      - Examples:
      ```
      attributes[SemanticConventions.Linux.memorySlabState.rawValue] = .reclaimable
      attributes[SemanticConventions.Linux.memorySlabState.rawValue] = .unreclaimable
      ```

     - Requires: Value should be one of ``MemorySlabStateValues`` (of type `String`)
    */
    case memorySlabState = "linux.memory.slab.state"

    /** 
      The Linux Slab memory state
    */
    public struct MemorySlabStateValues: CustomStringConvertible, Sendable {
      public static let reclaimable = MemorySlabStateValues("reclaimable") 
      public static let unreclaimable = MemorySlabStateValues("unreclaimable") 

      internal let value: String 

      public init(_ customValue: String) {
        self.value = customValue
      }

      public var description: String { 
        return value
      }
    }
  }
}