/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  public enum Mainframe: String {

    /**
     Name of the logical partition that hosts a systems with a mainframe operating system.

      - Examples:
      ```
      attributes[SemanticConventions.Mainframe.lparName.rawValue] = "LPAR01"
      ```

     - Requires: Value type should be `String`
    */
    case lparName = "mainframe.lpar.name"
  }
}