/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  public enum Nfs: String {

    /**
     NFSv4+ operation name.

      - Examples:
      ```
      attributes[SemanticConventions.Nfs.operationName.rawValue] = "OPEN"
      attributes[SemanticConventions.Nfs.operationName.rawValue] = "READ"
      attributes[SemanticConventions.Nfs.operationName.rawValue] = "GETATTR"
      ```

     - Requires: Value type should be `String`
    */
    case operationName = "nfs.operation.name"

    /**
     Linux: one of "hit" (NFSD_STATS_RC_HITS), "miss" (NFSD_STATS_RC_MISSES), or "nocache" (NFSD_STATS_RC_NOCACHE -- uncacheable)

      - Examples:
      ```
      attributes[SemanticConventions.Nfs.serverRepcacheStatus.rawValue] = "hit"
      ```

     - Requires: Value type should be `String`
    */
    case serverRepcacheStatus = "nfs.server.repcache.status"
  }
}