/*
 * Copyright The OpenTelemetry Authors 
 * SPDX-License-Identifier: Apache-2.0
 */

// DO **NOT** EDIT. This file is automatically generated.

import Foundation 

extension SemanticConventions {
  public enum OncRpc: String {

    /**
     ONC/Sun RPC procedure name.

      - Examples:
      ```
      attributes[SemanticConventions.OncRpc.procedureName.rawValue] = "OPEN"
      attributes[SemanticConventions.OncRpc.procedureName.rawValue] = "READ"
      attributes[SemanticConventions.OncRpc.procedureName.rawValue] = "GETATTR"
      ```

     - Requires: Value type should be `String`
    */
    case procedureName = "onc_rpc.procedure.name"

    /**
     ONC/Sun RPC procedure number.

     - Requires: Value type should be `Int`
    */
    case procedureNumber = "onc_rpc.procedure.number"

    /**
     ONC/Sun RPC program name.

      - Examples:
      ```
      attributes[SemanticConventions.OncRpc.programName.rawValue] = "portmapper"
      attributes[SemanticConventions.OncRpc.programName.rawValue] = "nfs"
      ```

     - Requires: Value type should be `String`
    */
    case programName = "onc_rpc.program.name"

    /**
     ONC/Sun RPC program version.

     - Requires: Value type should be `Int`
    */
    case version = "onc_rpc.version"
  }
}