receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*

exporters:
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    sending_queue:
      batch:
  prometheus:
    endpoint: "0.0.0.0:9464"

processors:
  resource:
    attributes:
      - key: service.name
        value: OTLP Exporter
        action: insert

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
      processors: [resource]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
      processors: [resource]
