name: Scope Testing

on: [push]

jobs:
  scope:
    runs-on: macOS-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Scope for Swift
        uses: undefinedlabs/scope-for-swift-action@v1
        with:
          dsn: ${{ secrets.SCOPE_DSN }}
          platform: macos
          codePath: true
          
