# This workflow will build the project nightly to try to detect issues early

name: Nightly Integration Build

on:
  schedule:
  - cron: 0 4 * * *
  workflow_dispatch:

jobs:
 macOS:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: 16.4
    - name: Build for macOS
      run: swift build
  iOS:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: 16.4
    - name: Install Homebrew kegs
      run: make setup-brew
    - name: Build for iOS
      run: make build-ios
  tvOS:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: 16.4
    - name: Install Homebrew kegs
      run: make setup-brew
    - name: Build for tvOS
      run: make build-tvos
  watchOS:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: 16.4
    - name: Install Homebrew kegs
      run: make setup-brew
    - name: Build for watchOS
      run: make build-watchos
  visionOS:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: 16.4
    - name: Install Homebrew kegs
      run: make setup-brew
    - name: Build for visionOS
      run: make build-visionos
  linux:
    runs-on: ubuntu-latest
    container: swift:6.1@sha256:e2a8181242cbffdb3ada767da44d1bc6681bad37f03525f5b7165f6421806ca3
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Build tests for Linux
        run: swift build
