name: Warn Release Pull Requests
on:
  pull_request:
    branches:
      - main
    types:
      - opened
permissions:
  contents: read
jobs:
  Check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps: 
      - name: check branch name
        id: check-release
        run: |
          if [[ ${{ github.head_ref }} =~ ^release/([0-9]+\.[0-9]+\.[0-9]+$) ]]; then
            echo "match=true" >> $GITHUB_OUTPUT
          fi
      - name: add comment if PR is release 
        if: steps.check-release.outputs.match == 'true'
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
        with:
          message: |
            **WARNING** : This PR will trigger a release and tag when merged.
