name: Tag & Note Release
on : 
  pull_request:    
    branches:
      - main
    types:
      - closed
concurrency:
  group: tag-note-release-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
jobs:
  tag:
    name: Create Tag & Release
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: macos-latest
    permissions:
      contents: write # required for creating tags and releases
    outputs:
      version: ${{ steps.parse.outputs.version }}
    steps:
      - name: Parse version from branch name
        id: parse
        run: |
          version=$(echo "${{ github.event.pull_request.head.ref }}" | sed 's/^release\///')
          echo "version=$version" >> $GITHUB_OUTPUT
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'
      - name: Check if tag already exists
        id: tag_check
        run: |
          if git rev-parse "refs/tags/${{ steps.parse.outputs.version }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Create tag
        if: steps.tag_check.outputs.exists == 'false'
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: version bump to ${{ steps.parse.outputs.version }}
          tagging_message: '${{ steps.parse.outputs.version }}'
      - name: Create release
        if: steps.tag_check.outputs.exists == 'false'
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with: 
          tag: ${{ steps.parse.outputs.version }}
          prerelease: true
          generateReleaseNotes: true
  
  cocoapods:
    name: Publish to CocoaPods
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release/')
    needs: tag
    uses: ./.github/workflows/Push-CocoaPods.yml
    with:
      version: ${{ needs.tag.outputs.version }}
    secrets: inherit
