name: Tag & Note Release
on : 
  pull_request:    
    branches:
      - main
    types:
      - closed
jobs:
  TagRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Check if merge is release branch
        id: check-release
        run: |
          if [[ ${{ github.head_ref }} =~ ^release/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "match=true" >> $GITHUB_OUTPUT
          fi
      - name: Tag if
        if: github.event.pull_request.merged == true &&  steps.check-release.outputs.match == true
        run: echo This is a release branch ${{ github.head_ref }}     
    
