name: Update Core Dependencies

on:
  workflow_dispatch:
    inputs:
      core_version:
        description: 'OpenTelemetry-swift-core version to update to'
        required: true
        type: string
      create_pr:
        description: 'Create pull request with changes'
        required: false
        default: true
        type: boolean

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Validate version format
        run: |
          if [[ ! "${{ github.event.inputs.core_version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.-]+)?(\+[a-zA-Z0-9.-]+)?$ ]]; then
            echo "Error: Version must follow semantic versioning"
            exit 1
          fi

      - name: Update dependencies
        run: |
          ./Scripts/versioning/update_core_dependencies.sh "${{ github.event.inputs.core_version }}"

      - name: Check for changes
        id: changes
        run: |
          if [[ -n $(git diff --name-only) ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true' && github.event.inputs.create_pr == 'true'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          commit-message: |
            Update opentelemetry-swift-core dependencies to ${{ github.event.inputs.core_version }}
            
            - Updated Package.swift dependency version
            - Updated all .podspec files with new core dependency versions
          title: "Update core dependencies to ${{ github.event.inputs.core_version }}"
          body: |
            This PR updates the openTelemetry-swift-core dependencies to version `${{ github.event.inputs.core_version }}`.

            ## Changes
            - Updated `Package.swift` to use core version `${{ github.event.inputs.core_version }}`
            - Updated all `.podspec` files to reference core dependencies at version `${{ github.event.inputs.core_version }}`

            Auto-generated by update-core-dependencies workflow.
          branch: update-core-deps-${{ github.event.inputs.core_version }}
          delete-branch: true

      - name: Output result
        run: |
          if [[ "${{ steps.changes.outputs.has_changes }}" == "true" ]]; then
            echo "Dependencies updated to version ${{ github.event.inputs.core_version }}"
            if [[ "${{ github.event.inputs.create_pr }}" == "true" ]]; then
              echo "Pull request created"
            else
              echo "Changes committed but no PR created"
            fi
          else
            echo "No changes detected - dependencies might already be at version ${{ github.event.inputs.core_version }}"
          fi